disabled_rules:
  - multiple_closures_with_trailing_closure
  - trailing_whitespace
type_name:
  max_length: # warning and error
    warning: 40
    error: 50
  allowed_symbols: ["_"]
identifier_name:
  min_length: 1
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 500
  error: 1200
excluded:
  - Tetris-SwiftUI/DerivedData
